// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace hammyoncoffeine.Website {
	
	
	public partial class Admin_UserControls_activate {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlInputText userName;
		
		protected System.Web.UI.HtmlControls.HtmlInputText passWord1;
		
		protected System.Web.UI.HtmlControls.HtmlInputText passWord2;
		
		protected System.Web.UI.HtmlControls.HtmlInputText surname;
		
		protected System.Web.UI.HtmlControls.HtmlInputText name;
		
		protected System.Web.UI.HtmlControls.HtmlInputText phoneNumber;
		
		protected System.Web.UI.WebControls.Button save;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl message;
	}
}
