// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace hammyoncoffeine.Website {
	
	
	public partial class Admin_UserControls_files {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.PlaceHolder filesPlaceHolder;
		
		protected System.Web.UI.WebControls.FileUpload filePath;
		
		protected System.Web.UI.WebControls.Button upload;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl file_message;
		
		protected System.Web.UI.HtmlControls.HtmlInputText folderName;
		
		protected System.Web.UI.WebControls.Button createFolder;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl folder_message;
	}
}
