// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace hammyoncoffeine.Website {
	
	
	public partial class Admin_UserControls_files_directory {
		
		protected System.Web.UI.WebControls.PlaceHolder controlsPlaceHolder;
		
		protected System.Web.UI.WebControls.Button deleteFolder;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl foldersUL;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl filesUL;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl messageUL;
	}
}
