// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace hammyoncoffeine.Website {
	
	
	public partial class Admin_UserControls_myaccount {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlInputText oldPassWord;
		
		protected System.Web.UI.HtmlControls.HtmlInputText passWord1;
		
		protected System.Web.UI.HtmlControls.HtmlInputText passWord2;
		
		protected System.Web.UI.HtmlControls.HtmlInputText emailAddress;
		
		protected System.Web.UI.HtmlControls.HtmlInputText surname;
		
		protected System.Web.UI.HtmlControls.HtmlInputText lastname;
		
		protected System.Web.UI.HtmlControls.HtmlInputText address;
		
		protected System.Web.UI.HtmlControls.HtmlInputText postcode;
		
		protected System.Web.UI.HtmlControls.HtmlInputText location;
		
		protected System.Web.UI.HtmlControls.HtmlInputText phoneNumber;
		
		protected System.Web.UI.HtmlControls.HtmlInputText mobileNumber;
		
		protected System.Web.UI.HtmlControls.HtmlInputText website;
		
		protected System.Web.UI.HtmlControls.HtmlInputCheckBox notifications;
		
		protected System.Web.UI.WebControls.Button save;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl message;
	}
}
