// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace hammyoncoffeine.Website {
	
	
	public partial class Admin_type_kontakt {
		
		protected System.Web.UI.WebControls.TextBox emailAddress;
		
		protected System.Web.UI.WebControls.TextBox smtpServer;
		
		protected System.Web.UI.WebControls.TextBox portNumber;
		
		protected System.Web.UI.WebControls.TextBox username;
		
		protected System.Web.UI.WebControls.TextBox password;
		
		protected System.Web.UI.WebControls.TextBox subjectPrefix;
		
		protected System.Web.UI.WebControls.Button save;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl message;
	}
}
