// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace hammyoncoffeine.Website {
	
	
	public partial class Admin_UserControls_type_text {
		
		protected System.Web.UI.WebControls.TextBox txtContent;
		
		protected System.Web.UI.WebControls.Button save;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl message;
	}
}
