// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace hammyoncoffeine.Website {
	
	
	public partial class Admin_UserControls_users {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.PlaceHolder usersPlaceHolder;
		
		protected System.Web.UI.HtmlControls.HtmlInputText userName;
		
		protected System.Web.UI.HtmlControls.HtmlInputText emailAddress;
		
		protected System.Web.UI.WebControls.Button save;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl message;
	}
}
